---
# tasks file for firewall
#- name: include os specific variables
#  include_vars: "{{ ansible_os_family }}.yml"

- name: Include RedHat specific tasks
  include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include Debian specific tasks
  include: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Check for unsupported target operating system
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported."
  when: firewall_supported_os is not defined
