---
- name: >
    RedHat | set_fact
      firewall_supported_os: True
  set_fact:
    firewall_supported_os: True

- name: template iptables
  template: src=iptables.j2 dest=/etc/sysconfig/iptables owner=root group=root mode=0644
  notify: restart iptables
